### ISSUE TITLE
hoistToFunctor and hoistFromFunctor usage

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander#4]
When looking through Control.Monad.Commander and Options.Commander, I could find no instances of hoistToFunctor and hoistFromFunctor being put to use.

Was there a purpose for these functions being defined or are they practice for fitting into the Freer Mondad that is Functor free?

**Comment by SamuelSchlesinger** [comment]
They are sort of fiddly functions you might want to use if you've got a large CLI you'd like to munge. The latter question is unclear to me, sadly. Perhaps ask differently?

**Comment by BebeSparkelSparkel** [comment]
I think this is related to SamuelSchlesinger/commander-cli#14
