### ISSUE TITLE
Support Errors without mtl

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [SamuelSchlesinger/commander#5]
Since CommanderT is related to Freer concepts, it would be nice to be able to capture failure conditions without mtl. Perhaps adding 

```haskell
data CommanderT e state f a
  = Defeat e
  ...

runCommanderT :: ... -> m (Maybe a)
runEitherCommanderT :: ... -> m (Either e a)
```

**Comment by SamuelSchlesinger** [comment]
I'd take a PR for this, with an accompanying one to commander-cli, but I'm not totally sure I'd accept it. What does the applicative instance look like? It's a bit fiddly, you have to make sure you use the "rightmost" Applicative instance and not the "combine" or "validate" Applicative instance.
